# DONE BY: Shah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website  # This label matches the service selector above
    spec:
      containers:
      - name: website
        image: mangosteen221/team5-web-app:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 3000