# DONE BY: Shah
apiVersion: v1
kind: Service
metadata:
  name: team5-service
spec:
  type: LoadBalancer
  selector:
    app: website      # <--- CHANGED: Now matches the label in your deployment
  ports:
    - protocol: TCP
      port: 80        # The public port (http://external-ip:80)
      targetPort: 3000 # The container port (must match containerPort in deployment)